name: Catapult

options:
  usesTabs: true

targets:
  Catapult:
    type: application
    platform: iOS
    sources: [Catapult]
    scheme:
      testTargets:
        - CatapultTests
  CatapultTests:
    type: bundle.unit-test
    platform: iOS
    sources: CatapultTests

